Repository PoCInnovation/GinGen, pull requests merged in 2023-03, with the labels that each got.

#17 Rework json
  .github/workflows/functionnal-tests.yml
  .gitignore
  functionnal_tests/default_output.json
  functionnal_tests/testing_file
  main.go
  parser_test.go
  src/HandlerParser/models.go
  src/HandlerParser/parser.go
  src/InfoParser/models.go
  src/convertJson.go
  test_data/endpoint.txt
  test_data/handler.txt
Labels: bug, enhancement

#20 Demonstration and README
  .github/workflows/functionnal-tests.yml
  README.md
  demo/components.json
  demo/demo.sh
  demo/output.json
  demo/testing_file
  functionnal_tests/default_output.json
  functionnal_tests/testing_file
  go.mod
  go.sum
  main.go
  src/Warning/checkWarning.go
  src/argumentGetter.go
  src/convertJson.go
  src/fileHandler.go
  src/src_test.go
Labels: documentation, enhancement, major

#21 fix(README): Added back wat was lost
  .github/assets/swagger-logo.png
  .github/assets/swagger-ui-result.png
  .github/assets/swagger-ui-route.png
  README.md
Labels: documentation, patch
